@rootURL = http://localhost:8000/api/v1

@userApi = {{rootURL}}/users
@categoryApi = {{rootURL}}/categories

#========== user api

### login user
POST {{userApi}}/signin
ContecategoryApint-Type: application/json

{
    "email": "rabin9087@gmail.com",
    "password": "Rabin@9087"
}

### get user profile
GET {{userApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0
Content-Type: application/json

### OTP request
POST {{userApi}}/request-otp
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0
Content-Type: application/json

{
    "email": "rabin9087@gmail.com"
}
### update password
PATCH  {{userApi}}/password
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzIwNjUsImV4cCI6MTcwNTM3Mjk2NX0.NfufQ7qzpTU7ySC73LhbSmGLzwDcpTfpqc0hyXMXp-Q
Content-Type: application/json

{
    "oldPassword": "Rabin@123",
    "newPassword": "Rabin@9087"
}


#========user api
###C
POST  {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0
Content-Type: application/json

{
    "title": "Mobile"
}


###R
GET   {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0
Content-Type: application/json


###U
PUT   {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0
Content-Type: application/json

{
    "_id": "65a6039ff4881b6724719fc3",
    "title": "Laptop",
    "status": "active"
}

###D
DELETE   {{categoryApi}}/65a6039ff4881b6724719fc3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhYmluOTA4N0BnbWFpbC5jb20iLCJpYXQiOjE3MDUzNzgyNzEsImV4cCI6MTcwNTM3OTE3MX0.4K1FvVUtAOpOK-XWW7xZsMbTWzIXF-hyuKuQUaagPA0


